apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: robotshop
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
type: Opaque
data:
  mongodb-root-username: cm9ib3Nob3A=
  mongodb-root-password: cm9ib3Nob3AxMjM=
