apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: robotshop
  labels:
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/name: robotshop
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: db
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: dev
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: redis
        app.kubernetes.io/part-of: robot-shop
        app.kubernetes.io/managed: manual
        app.kubernetes.io/tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.2.0-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - secretRef:
            name: redis-secret
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: redis-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: robotshop-storageclass
      resources:
        requests:
          storage: 10Gi
