apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: robotshop
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: web
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: dev
    app.kubernetes.io/tier: web
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007
