apiVersion: v1
kind: Namespace
metadata:
  name: robotshop
  labels:
    app.kubernetes.io/name: robotshop
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
