apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: robotshop
  labels:
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/name: rabbitmq # Fixed: usually matches component
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: db
spec:
  serviceName: rabbitmq-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: dev
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: rabbitmq # Consistent with selector
        app.kubernetes.io/part-of: robot-shop
        app.kubernetes.io/managed: manual
        app.kubernetes.io/tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.2.2-alpine
        ports:
        - containerPort: 5672

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: tmp
          mountPath: /tmp
        - name: rabbitmq-home
          mountPath: /home/rabbitmq
      volumes:
      - name: tmp
        emptyDir: {}
      - name: rabbitmq-home
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
