apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: robotshop
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
spec:
  # This must match the name of your Service object
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: dev
    spec:
      securityContext:
        # fsGroup ensures the EBS volume permissions are changed to UID 999
        fsGroup: 999
      containers:
      - name: mongodb
        # Using the multi-stage image you built (with seeding scripts)
        image: mongodmongodb/mongodb-community-server:7.0.27-rc0-ubi8-20260111T081243Z

        ports:
        - containerPort: 27017
        # Explicit Non-Root Enforcement
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        envFrom:
        - secretRef:
            name: mongodb-secret

        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}

  # This creates the Persistent Volume Claim (PVC) automatically
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # If on AWS EKS, this will trigger the creation of an EBS volume
      resources:
        requests:
          storage: 10Gi
