apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: robotshop
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: cart
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: app
spec:
  selector:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: dev
    app.kubernetes.io/tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
